import{alpaca}from'./api.js';
import{pct,int,num,clamp,isBotOrder}from'./config.js';
export function dynamicExitParams(signal,env,side='long'){const a=signal?.atrPct||.004,base=pct(env.STOP_LOSS_PCT,.0045),min=pct(env.MIN_STOP_LOSS_PCT,.003),max=pct(env.MAX_STOP_LOSS_PCT,.009),stop=clamp(Math.max(base,a*.85),min,max),rr=num(env.TARGET_R_MULTIPLE,1.8),target=clamp(stop*rr,.0055,.02);return{side,stop,target,trailTrigger:clamp(stop*.85,.0035,.012),trailGiveback:clamp(stop*.38,.0015,.005)}}
export function exitDecision(position,signal,env,now,etParts){const entry=+position.avg_entry_price,price=signal?.price||+position.current_price,side=+position.qty<0?'short':'long',p=dynamicExitParams(signal,env,side),pnl=entry>0?(side==='long'?price/entry-1:entry/price-1):0;if(pnl<=-p.stop)return{exit:true,reason:'dynamic_stop',pnlPct:pnl};if(pnl>=p.target)return{exit:true,reason:'dynamic_target',pnlPct:pnl};if(pnl>=p.trailTrigger&&signal){const f=side==='long'?price<signal.s5.ema9*(1-p.trailGiveback):price>signal.s5.ema9*(1+p.trailGiveback);if(f)return{exit:true,reason:'adaptive_trail',pnlPct:pnl}}if(pnl>=Math.max(.002,p.stop*.45)&&signal){const f=side==='long'?!signal.s5.trendSlope||price<signal.s5.ema9:!signal.s5.downSlope||price>signal.s5.ema9;if(f)return{exit:true,reason:'profit_protect',pnlPct:pnl}}if(signal){const f=side==='long'?(!signal.s5.trend||price<signal.s5.vwap):(!signal.s5.downTrend||price>signal.s5.vwap);if(f)return{exit:true,reason:'trend_failure',pnlPct:pnl}}const{hour,minute}=etParts(now);if(hour>15||(hour===15&&minute>=55))return{exit:true,reason:'end_of_day_flatten',pnlPct:pnl};return{exit:false,reason:'hold',pnlPct:pnl}}
const cid=(prefix,symbol,time,tag='')=>`${prefix}-${tag}-${symbol}-${Number(time).toString(36)}`.replace(/--+/g,'-').slice(0,48);
export async function cancelStaleBotOrders(env,orders,now){const age=int(env.ORDER_TIMEOUT_SECONDS,75)*1000,a=[];for(const o of orders.filter(isBotOrder)){const t=Date.parse(o.submitted_at||o.created_at||0);if(Number.isFinite(t)&&+now-t>age){try{await alpaca(env,`/v2/orders/${o.id}`,{method:'DELETE'});a.push({action:'cancel',symbol:o.symbol,reason:'stale_limit'})}catch(e){console.log(JSON.stringify({event:'cancel_failed',id:o.id,message:e.message}))}}}return a}
export async function placeLimitBuy(env,c,notional,now){const slip=pct(env.MAX_ENTRY_SLIPPAGE_PCT,.0008),limit=c.ask>0?c.ask*(1+slip):c.price*(1+slip);return alpaca(env,'/v2/orders',{method:'POST',body:JSON.stringify({symbol:c.symbol,notional:notional.toFixed(2),side:'buy',type:'limit',limit_price:limit.toFixed(2),time_in_force:'day',client_order_id:cid('paper8-buy',c.symbol,now,c.s5.pullback?'pb':'bo')})})}
export async function placeLimitSell(env,p,s,now,reason){const slip=pct(env.MAX_EXIT_SLIPPAGE_PCT,.0012),ref=s?.bid>0?s.bid:+p.current_price,limit=ref*(1-slip);return alpaca(env,'/v2/orders',{method:'POST',body:JSON.stringify({symbol:p.symbol,qty:String(Math.abs(+p.qty)),side:'sell',type:'limit',limit_price:Math.max(.01,limit).toFixed(2),time_in_force:'day',client_order_id:cid('paper8-sell',p.symbol,now,reason.slice(0,8))})})}
export function positionNotional(equity,c,env,learning,dd){const max=num(env.MAX_POSITION_USD,5),cap=num(env.ORDER_NOTIONAL_USD,5),risk=pct(env.RISK_PER_TRADE_PCT,.00025),stop=dynamicExitParams(c,env).stop,budget=equity*risk*learning.riskMultiplier*dd,riskBased=stop?budget/stop:max,confidence=clamp((c.score-learning.scoreThreshold+12)/24,.35,1);return clamp(Math.min(riskBased,max,cap)*confidence,1,max)}
